# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: configuredatabricks@0
  inputs:
    url: 'https://adb-7796938190559016.16.azuredatabricks.net/'
    token: '$(workspaceSecrets)'

- script: |
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pip install pyspark pandas numpy
    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml $(Build.Repository.LocalPath)/dataOps/Test.py || true
  displayName: 'pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: deploynotebooks@0
  inputs:
    notebooksFolderPath: 'dataOps'
    workspaceFolder: '/Users/a-ericchien@microsoft.com'

- task: executenotebook@0
  inputs:
    notebookPath: '/Users/a-ericchien@microsoft.com/Main'